name: First-workflow

on: workflow_dispatch

jobs:
  first_workflow_job:
       runs-on: ubuntu-latest
       steps:
          - name: Displays the node version
            run: node -v
            
          - name: print hello world in pipeline 
            run: echo "Hello-world"
          

